name: Build/release

on: push

jobs:
  arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [arm64]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pkg
        run: npm i -g pkg

      - name: Frontend yarn
        run: cd ezshare-frontend && yarn

      - name: yarn
        run: yarn

      - name: Build
        run: npm run build

      - name: Patch
        run: patch -p1 < standalone.patch

      - name: Run pkg
        run: |
          mv ezshare-frontend/src/App-arm64.js ezshare-frontend/src/App.js
          mkdir ezshare
          rm -r node_modules/clipboardy/fallbacks
          pkg . --targets=node16-linux-arm64 --output=ezshare/ezshare
          zip -r ezshare-1.9.0-linux-aarch64-zh.zip ezshare

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: arm64-artifact
          path: ezshare-1.9.0-linux-aarch64-zh.zip

  x86-64:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install pkg
        run: npm i -g pkg

      - name: Frontend yarn
        run: cd ezshare-frontend && yarn

      - name: yarn
        run: yarn

      - name: Build
        run: npm run build

      - name: Patch
        run: patch -p1 < standalone.patch

      - name: Run pkg
        run: |
          mkdir ezshare
          mv node_modules/clipboardy/fallbacks/linux/xsel ezshare/clipboard
          rm -r node_modules/clipboardy/fallbacks
          pkg . --targets=node12-linux-x64 --output=ezshare/ezshare
          zip -r ezshare-1.9.0-linux-x86-64-zh.zip ezshare

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: x86-64-artifact
          path: ezshare-1.9.0-linux-x86-64-zh.zip

  release:
    needs: [arm64, x86-64]
    runs-on: ubuntu-latest

    steps:
      - name: Download arm64 artifact
        uses: actions/download-artifact@v2
        with:
          name: arm64-artifact
          path: .

      - name: Download x86-64 artifact
        uses: actions/download-artifact@v2
        with:
          name: x86-64-artifact
          path: .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ezshare-1.9.0-linux-aarch64-zh.zip
            ezshare-1.9.0-linux-x86-64-zh.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
